[[providers]]
name = "python"
version = "3.11"

[[providers]]
name = "nginx"
version = "stable"

[config.files]
"nginx.conf" = "/etc/nginx/nginx.conf"
"start.sh" = "/app/start.sh"

[phases.build]
commands = [
    "pip install -r requirements.txt",
    "chmod +x /app/start.sh",
]

[start]
command = "/app/start.sh"