# nixpacks.toml

providers = ["python"]

[phases.setup]
aptPkgs = ["nginx", "supervisor"]
# If using a Nix based environment, replace aptPkgs with:
# nixPkgs = ["...", "nginx", "supervisor"]


# [phases.build]
# cmds = ["echo 'No build steps required'"]

[start]
# Use supervisor.conf (matching your filename)
cmd = "supervisord -n -c /app/supervisor.conf"