# nixpacks.toml

providers = ["python"]

[phases.setup]
# Install Nginx and Supervisor system packages
aptPkgs = ["nginx", "supervisor"]
# If using a Nix based environment, replace aptPkgs with:
# nixPkgs = ["...", "nginx", "supervisor"]

[phases.install]
# Nixpacks should automatically detect and install from requirements.txt
# Ensure 'flask' and 'gunicorn' are in requirements.txt

# [phases.build]
# Add custom build steps if needed (e.g., collect static files)
# cmds = ["echo 'No build steps required'"]

[start]
# Use supervisor.conf (matching your filename)
# Supervisord runs in foreground (-n) using the config file in /app
cmd = "supervisord -n -c /app/supervisor.conf"